version: '2'

services:
  db:
    container_name: db
    build: api/database/postgres
    ports:
     - "5432:5432"
    networks:
     - labelcraft

  frontend:
    container_name: frontend
    build: www
    ports:
     - "80:9000"
    depends_on:
     - db
    networks:
     - labelcraft

  api:
    container_name: api
    build: api
    ports:
     - "3000:3000"
    restart: always
    depends_on:
     - db
     - frontend
    environment:
     - RAILS_ENV=docker
    networks:
     - labelcraft

networks:
  labelcraft:
    driver: bridge
