version: '2'
<<<<<<< HEAD

services:
  db:
    container_name: db
    build: api/database/postgres
    ports:
     - "5432:5432"
    networks:
     - labelcraft

  frontend:
    container_name: frontend
    build: www
    ports:
     - "80:9000"
    depends_on:
     - db
    networks:
     - labelcraft

  api:
    container_name: api
    build: api
    ports:
     - "3000:3000"
    restart: always
    depends_on:
     - db
     - frontend
    environment:
     - RAILS_ENV=docker
    networks:
     - labelcraft

networks:
  labelcraft:
    driver: bridge
=======
services:
  frontend:
    image: labelcraft_frontend
    ports:
     - "80:9000"
  db:
    image: labelcraft_db
    ports:
     - "5432:5432"
  api:
    image: labelcraft_api
    depends_on:
     - db
    ports:
     - "3000:3000"
    environment:
     - RAILS_ENV=docker

networks:
  default:
    ipam:
      config:
       - subnet: 10.10.10.0/24
>>>>>>> a3cbeb1dfaffbb486b1d1831e49b4c3018906359
